### ISSUE TITLE
Does not create image

### ISSUE THREAD

**Issue by hasib-haque** [myllynen/rhel-image#5]
I changed the below parameters in the playbook and used ansible pull to run the playbook but the image  does not get created in /tmp/images:
rhel_image_git_remote_repo: https://gitlab.com/myblueprints.git
rhel_image_output_type: ami

There is no error in the ansible run

**Comment by myllynen** [comment]
I just updated the example blueprint to use RHEL 8.7 and tried building qcow2 and ami images on a RHEL 8 host, both seemed to work ok so I'm not sure what's going on here. If you check the build host, do you have an empty `/tmp/images` or no output directory at all? Thanks.

**Comment by myllynen** [comment]
I might have 'main' instead of 'master' branch, the default was set before the wide migration 'master' to 'main' began.

**Comment by hasib-haque** [comment]
Thanks, changing it to 'main' let the playbook run to the finish without errors, but I have an image in the  '.raw' format even though I set it 'rhel_image_output_type: ami'. Wondering why

**Comment by myllynen** [comment]
Great to hear it's working now. At least for the time being RHEL Image Builder always creates raw images for AWS:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/composing_a_customized_rhel_system_image/index#composer-output-formats_composer-description

Thanks.
