### ISSUE TITLE
Image build process in infinite running state

### ISSUE THREAD

**Issue by hasib-haque** [myllynen/rhel-image#7]
I started having this issue recently, using the latest code from this repo. My blueprint file is also pretty basic. Not sure what's going to resolve this. 

TASK [Download image from osbuilder] *******************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["composer-cli", "compose", "image", "4c15ab13-f48d-4ab2-a1b5-5c33f59b9a82"], "delta": "0:00:00.024304", "end": "2023-05-16 14:17:29.163723", "msg": "non-zero return code", "rc": 1, "start": "2023-05-16 14:17:29.139419", "stderr": "ERROR: BuildInWrongState: Build 4c15ab13-f48d-4ab2-a1b5-5c33f59b9a82 is in wrong state: RUNNING", "stderr_lines": ["ERROR: BuildInWrongState: Build 4c15ab13-f48d-4ab2-a1b5-5c33f59b9a82 is in wrong state: RUNNING"], "stdout": "", "stdout_lines": []}

PLAY RECAP *****************************************************************

Blueprint file:
#
# Base definition
#
name = "base-image"
description = "Base Image"
version = "2023.03.13"
distro = "rhel-87"

#
# Boot parameters
#
[customizations.kernel]
append = "no_timer_check console=hvc0 LANG=en_US.UTF-8 console=ttyS0,115200n8 elevator=noop net.ifnames=0 biosdevname=0"

#
# Filesystem
#
[[customizations.filesystem]]
mountpoint = "/boot"
size = "1 GiB"
[[customizations.filesystem]]
mountpoint = "/"
size = "8 GiB"
[[customizations.filesystem]]
mountpoint = "/home"
size = "2 GiB"
[[customizations.filesystem]]
mountpoint = "/tmp"
size = "2 GiB"
[[customizations.filesystem]]
mountpoint = "/var"
size = "8 GiB"
[[customizations.filesystem]]
mountpoint = "/var/log"
size = "2 GiB"
[[customizations.filesystem]]
mountpoint = "/var/log/audit"
size = "2 GiB"
[[customizations.filesystem]]
mountpoint = "/var/tmp"
size = "2 GiB"

#
# Locale

#
# Timezone
#
[customizations.timezone]
timezone = "America/New_York"

# Groups
[[groups]]
name="Minimal Install"

[[customizations.user]]
name = "ec2-user"
groups = ["wheel"]

**Comment by myllynen** [comment]
Not sure why this is showing up now if not earlier but since RHEL 8.8 released yesterday has some notable updates for Image Builder it might be a good idea to update to the latest RHEL packages and see if that helps.

If not, is the state RUNNING only for a period of time or does it seem to be stuck in that state? Thanks.

**Comment by hasib-haque** [comment]
Hi, I have updated and upgraded the RHEL packages on my build host which is a RHEL9 ec2 instance, also tried distro = "rhel-88" in the blueprint toml file, but the issue is still there unfortunately. The build process does not end and fills up the / directory. I have been feeding the verbose output to ChatGPT to debug, here is what I got:
TASK [Download image from osbuilder]: This task failed with an error. The command composer-cli compose image ec9b822c-2474-493c-9fe5-df41e95b2884 returned a non-zero exit code (rc=1), indicating an error. The specific error message states that the build with the ID ec9b822c-2474-493c-9fe5-df41e95b2884 is in the wrong state, specifically "RUNNING". This suggests that the build process is still in progress or encountered an issue during the build.
Thanks

**Comment by myllynen** [comment]
If the host / directory gets completely full it could in theory cause something like this and is certainly a corner case which probably haven't been tested by anyone. So I guess the question is, does / fill up during the regular build process or will it fill up only later when osbuilder is perhaps stuck logging something constantly?

**Comment by hasib-haque** [comment]
It fails without filling up, but it happens the other way too, i.e. keeps running and fills up the directory. For example, during my last run, it stopped before filling up 300 gb+ disk space.
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7.7G     0  7.7G   0% /dev
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           3.1G   33M  3.1G   2% /run
/dev/xvda4      400G  342G   58G  86% /
/dev/xvda3      495M  244M  251M  50% /boot
/dev/xvda2      200M   20K  200M   1% /boot/efi
tmpfs           1.6G     0  1.6G   0% /run/user/1000

**Comment by myllynen** [comment]
One thing that has changed around disk usage recently is handling the size parameter:

https://bugzilla.redhat.com/show_bug.cgi?id=2033192

With RHEL 8.7 (or 8.6) the parameter is interpreted differently, with latest versions e.g. 30720 means 30 GB.

If that's as expected here then it'd be probably best to collect a sosreport from the build host and create support ticket for Red Hat, certainly under no conditions a single build should fill up a 300 GB disk!
